### ISSUE TITLE
Error during the download statement 

### ISSUE THREAD

**Issue by armandossrecife** [haarsh85/pytube_youtube_downloader#1]
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
[<ipython-input-7-ba7a5dbf57d7>](https://localhost:8080/#) in <module>()
----> 9     res_480p = yt.streams.get_by_resolution('480p')

15 frames
[/usr/lib/python3.7/urllib/request.py](https://localhost:8080/#) in http_error_default(self, req, fp, code, msg, hdrs)
    647 class HTTPDefaultErrorHandler(BaseHandler):
    648     def http_error_default(self, req, fp, code, msg, hdrs):
--> 649         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    650 
    651 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 429: Too Many Requests

**Comment by haarshdev** [comment]
Hello @armandossrecife, thank you for the comment. I tried to replicate the issue, but everything was working without any error. Also tried with Python version 3.7.9 as well. I would appreciate if you could kindly give me steps to replicate the issue if possible. Did you make any modifications?
